from .mp3_metadata_embedder import MP3MetadataEmbedder
from .m4a_metadata_embedder import M4AMetadataEmbedder
from .flac_metadata_embedder import FLACMetadataEmbedder
from .ogg_metadata_embedder import OGGMetadataEmbedder
from .opus_metadata_embedder import OpusMetadataEmbedder